### ISSUE TITLE
Verificar funcionalidade com módulo HC-06 do Arduino

### ISSUE THREAD

**Issue by requeijaum** [requeijaum/climate_controller-client#2]
Ler issue do módulo Cordova que utilizo.

https://github.com/don/BluetoothSerial/issues/9

--------

**Comment by requeijaum** [comment]
Descobri hoje que o buffer do bluetoothSerial não estava sendo preenchido. O Arduino com HC-06 não consegue enviar o JSON completamente de uma vez só - logo ele constrói a string em 2 ou 3 buffers.

Alterei a função ```bluetoothSerial.read()``` para ```bluetoothSerial.readUntil("}")``` e obtive bons resultados!

Mas ainda não conseguimos fazer funcionar com o Arduino... apenas funciona com o simulador em Python.

**Comment by requeijaum** [comment]
Parece que o @1uuc4asb resolveu isso no commit https://github.com/requeijaum/climate_controller-client/commit/4db53f4c89b3624e3db7eb7b60514e75a23aa837

**Comment by lucastaonline** [comment]
Resolvido.
Usei a função readUntil("}") 
E como a mesma retorna uma promise, coloquei tudo que precisava da informação do read until dentro do seu then, e o problema foi resolvido.
Inicialmente, nosso problema era o buffer não sendo enviado completamente. Conseguimos resolver isso com o read until, mas erros ainda aconteciam. O problema é o código não espera pelo término da promise. Ele chama a promise, mas continua rodando, antes mesmo de termos o resultado na promise.
No caso, a gente tentava acessar as informações lidas do buffer, antes de terminarmos de ler. 
O problema foi resolvido encapsulando tudo que dependia desta promise.
